
import { Noto_Sans_JP } from "@next/font/google";


export const metadata = {
  title: 'About',
  description: 'Generated by create next app -about-',
}

const notojp = Noto_Sans_JP({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-notojp",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="jp">
      <body className={notojp.className}>{children}</body>
    </html>
  )
}
