export const metadata = {
  title: 'Info',
  description: 'Generated by create next app -info-',
}

export default function RootLayout({ children }) {
  return (
    <html lang="jp">
      <body>{children}</body>
    </html>
  )
}