import "./globals.css";
import { Noto_Sans_JP } from "next/font/google";

export const metadata = {
  title: "index",
  description: "Generated by create next app",
  openGraph: {
    title: "サイトのタイトル",
    description: "サイトの説明",
    images: ["/path-to-your-image.jpg"],
  },
};

const notojp = Noto_Sans_JP({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "notojp",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="jp">
      <body className={notojp.className}>{children}</body>
    </html>
  );
}
