export const metadata = {
  title: 'ニュース',
  description: 'Generated by create next app -ニュース-',
}

export default function RootLayout({ children }) {
  return (
    <html lang="jp">
      <body>{children}</body>
    </html>
  )
}